language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: I+yELY6zi6bBmwQ0N6Xok2ZaH/5t2fJTCqQa+C39Lg0YoUNCygqahSpOX57oeu6q984YOpcuIIZCMXYdIDAcRlgs37OwYoE+NC83QAzh0hNmoKHjwcQFGeLGIdJ5t0qMHCuqZYDFvqrPW35cbyxpgmC80P71JHaVWJ3e+pzGqp21khOX8XWAVe+VWBen607IQjfaPkCZV7kjF/BdbSdxpHxy+P8832UfrqBYsyu5jtiet5Kgspn08zF+KZjjlMGRl9Vtg0T96iyTVTTTX4PSRFUOwwac1/eBCV+ze+mHoty+CWx8YHkBPTVMt9T5EjmLdqsQ/MWn5pnumVV+0punSYWcsycd/TnRkAOQF6dujHG5KrXCU3R49g6j5xGQHoqk+meIgMZJVxP/ZW4sYJ0WDHVNerpBQ+F6ew8fv+HXFDkH3JfcOELduX9MyUyOC3RWSJIUP/BJ4aSG7tBiDxYh1JRZtPNgwK8OLs01Sd2wCoRz3HP2x19ZUa2CskF0rBn05TcKNJywm36oORyGbVG7aqbljSXVPDZCIW1VRvYFPktun9TZs4lohmo88dYEBEfHb5m1EdWGa94kkn5Y8ZWiSnfeb8gJvjoM+j0MwNIAMfOc98QQGPMV9mASHfKypZcadUwlWL453m0nPgYiYVw06gem7mFfsMJDyFxeVXZvLQ0=
